build:
  - id: clickhouse_sinker
    main: ./cmd/clickhouse_sinker
    binary: bin/clickhouse_sinker
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  draft: false
  target_commitish: '{{ .Commit }}'

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "checksums.txt"

nfpms:
  - vendor: clickhouse_sinker
    homepage: https://github.com/viru-tech/clickhouse_sinker
    maintainer: VIRU developers
    description: Sinker program that transfer kafka message into ClickHouse.
    license: MIT
    formats:
      - deb
      - rpm
    file_name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
