# https://github.com/golangci/golangci-lint-action
name: lint
on:
  push:
    tags: [ v* ]
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: --timeout=3m
